version: '3'

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    volumes:
      - ./mosquitto-config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ../letsencrypt/fullchain.pem:/mosquitto/certs/cert.pem
      - ../letsencrypt/privkey.pem:/mosquitto/certs/key.pem
      # - ./certs/cert.pem:/mosquitto/certs/cert.pem
      # - ./certs/key.pem:/mosquitto/certs/key.pem

    ports:
      - 1883:1883
      - 8883:8883
      - 8080:8080
      - 8081:8081
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ../letsencrypt/fullchain.pem:/etc/certs/cert.pem
      - ../letsencrypt/privkey.pem:/etc/certs/key.pem
      # - ./certs/cert.pem:/etc/certs/cert.pem
      # - ./certs/key.pem:/etc/certs/key.pem
      - ./html:/usr/share/nginx/html